//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTasks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleTasks.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string But_Add {
            get {
                return ResourceManager.GetString("But_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string But_Cancel {
            get {
                return ResourceManager.GetString("But_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string But_Del {
            get {
                return ResourceManager.GetString("But_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string But_Edit {
            get {
                return ResourceManager.GetString("But_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string But_Restore {
            get {
                return ResourceManager.GetString("But_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string But_Save {
            get {
                return ResourceManager.GetString("But_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiselect.
        /// </summary>
        public static string But_Select {
            get {
                return ResourceManager.GetString("But_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string But_Sort {
            get {
                return ResourceManager.GetString("But_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task list is empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Item_Alert {
            get {
                return ResourceManager.GetString("Item_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string Item_Alert_1 {
            get {
                return ResourceManager.GetString("Item_Alert_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 hours.
        /// </summary>
        public static string Item_Alert_12 {
            get {
                return ResourceManager.GetString("Item_Alert_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string Item_Alert_24 {
            get {
                return ResourceManager.GetString("Item_Alert_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 hours.
        /// </summary>
        public static string Item_Alert_3 {
            get {
                return ResourceManager.GetString("Item_Alert_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time limit:.
        /// </summary>
        public static string Item_End {
            get {
                return ResourceManager.GetString("Item_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Text.
        /// </summary>
        public static string Item_Icon {
            get {
                return ResourceManager.GetString("Item_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notification.
        /// </summary>
        public static string Item_Push {
            get {
                return ResourceManager.GetString("Item_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Item_Text {
            get {
                return ResourceManager.GetString("Item_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tasks.
        /// </summary>
        public static string Item_Title_Add {
            get {
                return ResourceManager.GetString("Item_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tasks.
        /// </summary>
        public static string Item_Title_Edit {
            get {
                return ResourceManager.GetString("Item_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual until: .
        /// </summary>
        public static string Main_List_End_Prefix {
            get {
                return ResourceManager.GetString("Main_List_End_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tasks.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Menu_Completed {
            get {
                return ResourceManager.GetString("Menu_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string Menu_Ended {
            get {
                return ResourceManager.GetString("Menu_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Set {
            get {
                return ResourceManager.GetString("Menu_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected task?.
        /// </summary>
        public static string Message_Del_Text {
            get {
                return ResourceManager.GetString("Message_Del_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Message_Del_Title {
            get {
                return ResourceManager.GetString("Message_Del_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty task.
        /// </summary>
        public static string Message_Empty_Text {
            get {
                return ResourceManager.GetString("Message_Empty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Empty_Title {
            get {
                return ResourceManager.GetString("Message_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore selected task?.
        /// </summary>
        public static string Message_Restore_Text {
            get {
                return ResourceManager.GetString("Message_Restore_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Message_Restore_Title {
            get {
                return ResourceManager.GetString("Message_Restore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed: .
        /// </summary>
        public static string Other_List_Comleted_Prefix {
            get {
                return ResourceManager.GetString("Other_List_Comleted_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired: .
        /// </summary>
        public static string Other_List_End_Prefix {
            get {
                return ResourceManager.GetString("Other_List_End_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed tasks.
        /// </summary>
        public static string Other_Title_Completed {
            get {
                return ResourceManager.GetString("Other_Title_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired tasks.
        /// </summary>
        public static string Other_Title_Ended {
            get {
                return ResourceManager.GetString("Other_Title_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable notifications.
        /// </summary>
        public static string Set_AlertBlock {
            get {
                return ResourceManager.GetString("Set_AlertBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main:.
        /// </summary>
        public static string Set_General {
            get {
                return ResourceManager.GetString("Set_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen:.
        /// </summary>
        public static string Set_Lock {
            get {
                return ResourceManager.GetString("Set_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired tasks first.
        /// </summary>
        public static string Set_Lock_EndFirst {
            get {
                return ResourceManager.GetString("Set_Lock_EndFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight expired tasks.
        /// </summary>
        public static string Set_Lock_EndSelect {
            get {
                return ResourceManager.GetString("Set_Lock_EndSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window:.
        /// </summary>
        public static string Set_Main {
            get {
                return ResourceManager.GetString("Set_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired tasks first.
        /// </summary>
        public static string Set_Main_EndFirst {
            get {
                return ResourceManager.GetString("Set_Main_EndFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight expired tasks.
        /// </summary>
        public static string Set_Main_EndSelect {
            get {
                return ResourceManager.GetString("Set_Main_EndSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting on startup.
        /// </summary>
        public static string Set_Sort {
            get {
                return ResourceManager.GetString("Set_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sorting.
        /// </summary>
        public static string Set_Sort_Last {
            get {
                return ResourceManager.GetString("Set_Sort_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name, A-Z.
        /// </summary>
        public static string Set_Sort_Name1 {
            get {
                return ResourceManager.GetString("Set_Sort_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by name, Z-A.
        /// </summary>
        public static string Set_Sort_Name2 {
            get {
                return ResourceManager.GetString("Set_Sort_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by time, older first.
        /// </summary>
        public static string Set_Sort_Time1 {
            get {
                return ResourceManager.GetString("Set_Sort_Time1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by time, newer first.
        /// </summary>
        public static string Set_Sort_Time2 {
            get {
                return ResourceManager.GetString("Set_Sort_Time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Set_Title {
            get {
                return ResourceManager.GetString("Set_Title", resourceCulture);
            }
        }
    }
}
